name: Setup Workspace
on:
  workflow_dispatch:

jobs:
  setup-directory:
    runs-on: [self-hosted]
    container:
      image: wang4649/wang-ubuntu:latest
      options: --user wang
    defaults:
      run:
        working-directory: /home/wang
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      
      - name: Create workspace structure
        run: |
          # 创建工作目录
          mkdir -p /home/wang/workdir/

    - name: update
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        cd /home/wang/workdir
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
      
      - name: Cleanup (容器自动清理)
        run: |
          echo "所有更改将在容器退出后自动清理"
