name: nx30pro 012 builder

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: .config
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: self-hosted
    container:
      image: wang4649/wang-ubuntu:latest
      options: --user wang -v /DATA/output:/home/wang
    env:
      HOME: /home/wang
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
      
      - name: 安装依赖
        env:
          DEBIN_FRONTEND：noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install \
          ack \
          antlr3 \
          asciidoc \
          autoconf \
          automake \
          autopoint \
          binutils \
          bison \
          build-essential \
          bzip2 \
          ccache \
          clang \
          cmake \
          cpio \
          curl \
          device-tree-compiler \
          flex \
          gawk \
          gcc-multilib \
          g++-multilib \
          gettext \
          genisoimage \
          git \
          gperf \
          haveged \
          help2man \
          intltool \
          libc6-dev-i386 \
          libelf-dev \
          libfuse-dev \
          libglib2.0-dev \
          libgmp3-dev \
          libltdl-dev \
          libmpc-dev \
          libmpfr-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libpython3-dev \
          libreadline-dev \
          libssl-dev \
          libtool \
          llvm \
          lrzsz \
          msmtp \
          ninja-build \
          p7zip \
          p7zip-full \
          patch \
          pkgconf \
          python3 \
          python3-pyelftools \
          python3-setuptools \
          qemu-utils \
          rsync \
          scons \
          squashfs-tools \
          subversion \
          swig \
          texinfo \
          uglifyjs \
          upx-ucl \
          unzip \
          vim \
          wget \
          xmlto \
          xxd \
          zlib1g-dev
      
      - name: 下载源码
        run: |
          cd /home/wang
          git clone $REPO_URL -b $REPO_BRANCH /home/wang/openwrt
      
      - name: 更新FEEDS
        run: cd /home/wang/openwrt && ./scripts/feeds update -a
      
      - name: 安装FEEDS
        run: cd /home/wang/openwrt && ./scripts/feeds install -a
      
      - name: 下载配置
        run: |
          [ -e files ] && mv files /home/wang/openwrt/files
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE /home/wang/openwrt/.config
          make defconfig
      
      - name: 预下载DL
        run: |
          cd /home/wang/openwrt
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
